services:
  - type: web
    name: django-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn src.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: src.settings.prod
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: backend-db
          property: connectionString

databases:
  - name: backend-db
    plan: free
